name: 'Docker Build and Push'
description: 'Build, tag and push Docker image to ECR using Buildx and caching'

inputs:
  ecr-repo:
    description: 'ECR repository URI'
    required: true
  app-name:
    description: 'Application name for tagging'
    required: true
  version:
    description: 'Application short version'
    required: true
  full-version:
    description: 'Application full version'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'
  build-args:
    description: 'Build arguments for Docker build'
    required: false
    default: ''
  platforms:
    description: 'Target platforms for the Docker image'
    required: false
    default: 'linux/amd64'

outputs:
  image:
    description: 'Built image tag'
    value: ${{ steps.build-push.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push with Docker Buildx
      id: build-push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: |
          ${{ inputs.ecr-repo }}:${{ inputs.app-name }}-${{ inputs.full-version }}
          ${{ inputs.ecr-repo }}:${{ inputs.app-name }}-${{ inputs.version }}
          ${{ inputs.ecr-repo }}:${{ inputs.app-name }}-latest
        cache-from: type=registry,ref=${{ inputs.ecr-repo }}:buildcache
        cache-to: type=registry,ref=${{ inputs.ecr-repo }}:buildcache,mode=max
        build-args: ${{ inputs.build-args }}