name: Backend Lint
description: 'Lint Go backend code using golangci-lint'

inputs:
  go-version:
    description: 'The Go version to set up'
    required: true

runs:
  using: "composite"

  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}

    - name: Run go mod tidy
      run: go mod tidy
      shell: bash
      working-directory: ${{ github.workspace }}/backend

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        working-directory: backend
        args: --timeout=3m