name: Backend Lint
description: 'Lint Go backend code using golangci-lint'

inputs:
  go-version:
    description: 'The Go version to set up'
    required: true

runs:
  using: "composite"

  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
        cache-dependency-path: backend/go.sum

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          backend/go.sum
        key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      shell: bash
      run: cd backend && go mod tidy

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        working-directory: backend
        args: --timeout=3m