name: 'Generate Semantic Version'
description: 'Generate semantic version with environment suffix'

inputs:
  tag-prefix:
    description: 'Tag prefix to identify version tags'
    required: true
  branch:
    description: 'Git branch name'
    required: true

outputs:
  version:
    description: 'Semantic version'
    value: ${{ steps.version.outputs.version }}
  full-version:
    description: 'Full version with environment and commit hash'
    value: ${{ steps.set-versions.outputs.full-version }}
  tag-name:
    description: 'Full tag name with prefix'
    value: ${{ steps.set-versions.outputs.tag-name }}

runs:
  using: "composite"
  steps:
    - name: Generate semantic version
      id: version
      uses: paulhatch/semantic-version@v5.4.0
      with:
        tag_prefix: ${{ inputs.tag-prefix }}
        major_pattern: '/(MAJOR)|(BREAKING CHANGE)/'
        minor_pattern: '/(feat)/'
        version_format: '${major}.${minor}.${patch}'

    - name: Set versions
      id: set-versions
      shell: bash
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        if [ "${{ inputs.branch }}" = "main" ]; then
          ENV_SUFFIX="prod"
        else
          ENV_SUFFIX="dev"
        fi
        VERSION="${{ steps.version.outputs.version }}"
        FULL_VERSION="${VERSION}-${ENV_SUFFIX}-${SHORT_SHA}"
        TAG_NAME="${{ inputs.tag-prefix }}${VERSION}-${ENV_SUFFIX}"
        
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "full-version=${VERSION}-${ENV_SUFFIX}-${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "tag-name=${TAG_NAME}" >> $GITHUB_OUTPUT
        
        echo "Version: ${VERSION}"
        echo "Full version: ${FULL_VERSION}"
        echo "Tag name: ${TAG_NAME}"