apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

patches:
  - path: service-patch.yaml
    target:
      kind: Service
      name: argocd-server
  
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm

labels:
  - pairs:
      environment: prod
      managed-by: kustomize